services:
  xboard:
    image: qukuan/xboard:0.0.1 # 镜像版本
    container_name: xboard # 本地创建容器名称
    restart: always
    networks:
      - 1panel-network # 1panel容器内部网络
    ports:
      - "127.0.0.1:9000:7001" # 宿主机监听端口号
    environment:
      - docker=true
      - RESOURCE_PROFILE=balanced
      - ENABLE_CADDY=true
      - ENABLE_WEB=true
      - ENABLE_HORIZON=true
      - ENABLE_WS_SERVER=true
      - ENABLE_REDIS=false # 关闭镜像内部Redis
      # Redis和PostgreSQL内部容器名称 端口号
      - DB_HOST=填你PostgreSQL内部容器名称
      - DB_PORT=5432
      - REDIS_HOST=填你Redis内部容器名称
      - REDIS_PORT=6379
    volumes:
      - ./.env:/www/.env
      - ./plugins:/www/plugins
      - ./.docker/.data/:/www/.docker/.data
      - ./storage/logs:/www/storage/logs

networks:
  1panel-network:
    external: true
  default:
    driver: bridge

